### ISSUE TITLE
Build Modules for Titanium

### ISSUE THREAD

**Issue by nubu** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#173]
Hi,

can anyone maybe create both (android/ios) modules for Titanium? I ran into several problems building them through studio.

Best, Nico

**Comment by Kirkkt** [comment]
Hi @nubu , we are in the process of refactoring the Titanium logic out of this repo. It can be found at https://github.com/BranchMetrics/Titanium-Deferred-Deep-Linking-SDK . 

Would you kindly check out this repo and see if it works for you? Thanks :)

**Comment by nuborian** [comment]
Hey, I'm not that familiar with this stuff.
I can't see how this should help me?

Last week i was able to build the ios module and i'm using it without any problem.

Now it just would be great if any of you guys could upload the android build module as a zip or something like this - so that i can use it there, too.

Cause i'm trying to build them with studio and terminal and both ways are not working. (i think because of some wrong confics on my machine or something like this -- > new mac)

Would be really really nice.

---
https://github.com/BranchMetrics/Titanium-Deferred-Deep-Linking-SDK
Maybe you could explain this a bit more, since there is nothing in the dist folder except 2 js files.
