### ISSUE TITLE
margin top with navbar when viewing in mobile

### ISSUE THREAD

**Issue by mderazon** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#205]
I have a website with a hidden navbar above the fold so that when you scroll below the fold it appears.

When adding Branch's smart banner `margin-top: 76px;` is being added to my `body` element that makes it look like this (only on mobile browser - ios / android)

![screen shot 2015-09-30 at 11 39 24 am](https://cloud.githubusercontent.com/assets/717076/10188430/f2413e82-6767-11e5-801f-730c73dfe927.png)

Any idea ?

**Comment by mandymcclausky** [comment]
@mderazon This is because of https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/blob/master/SMART_BANNER_GUIDE.md#playing-nicely-with-other-positon-fixed-sticky-banners, but the documentation makes it sound as though it's something that needs to be manually added in the CSS when in actuality they're already applying that 76px inline.

You will need to go into your CSS and add: `body.branch-banner-is-active { margin-top: 0 !important; }` in order to override it, though I do think either the docs need to be updated or this style should not be added by default.

**Comment by mderazon** [comment]
@mandymcclausky thanks for the link and the tip :tada:

**Comment by ricardoribas** [comment]
@mandymcclausky thanks for the answer. It solved my problem :)

**Comment by keepitreal** [comment]
If you're coming to this late (like I am) make sure your `body` tag isn't set to `position: relative` because the branch banner is `position: absolute`.
