### ISSUE TITLE
main - package.json

### ISSUE THREAD

**Issue by pgherveou** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#94]
Hello Branch
it seems there is an error in the npm package
your are specifying a `"main": "dist/web/build.min.js"` inside your package.json that does not exist when you install the package through npm, thus webpack and probably other package manager fail to install the dependency

**Comment by aaustin** [comment]
@pgherveou We just broke this repo down into 3 different ones: titanium, web and cordova. It's definitely still got a few kinks. I believe the correct path is "dist/build.min.js". Let me fix the repo!

**Comment by aaustin** [comment]
I think I've cleaned it up now - try now?

**Comment by tjanela** [comment]
I can confirm that this issue is solved on 3819cbf7ff1c1002222620c059922fd84a8aaa2d
Did this by:
`bower install 'https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK.git#3819cbf7ff'`
Nevertheless documentation on https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/blob/master/WEB_GUIDE.md
'Common.JS and RequireJS compatibility' section should be updated to contained the correct require name which seems to be 'branch-sdk'
@pgherveou is it solved on your end?

**Comment by pgherveou** [comment]
cool testing it now

**Comment by pgherveou** [comment]
repo seems to be fixed but can you push a new version on npm
https://www.npmjs.com/package/branch-sdk says the version is 4 days old

**Comment by pgherveou** [comment]
my build works fine when I copy the file at the right location so I think its just a matter of publishing the package now

**Comment by tjanela** [comment]
Hey @pgherveou they will probably batch this with other fixes.
@aaustin at your convenience let us know when we can expect this fix in a release.

**Comment by aaustin** [comment]
Hey team - we deployed the fixed version last night! Just FYI. Hope we're out of the woods now.

**Comment by tjanela** [comment]
Confirmed.
Version 1.6.6 work as intended.
Thanks @aaustin

**Comment by aaustin** [comment]
good stuff - thanks for the heads up guys
